const flags = Object.freeze({
    FLY: (1 << 0),
    SWIM: (1 << 1),
    CONVEYOR: (1 << 2),
    CLIENT: (1 << 3),
    INWATER: (1 << 4),
    MONSTER: (1 << 5),
    GODMODE: (1 << 6),
    NOTARGET: (1 << 7),
    SKIPLOCALHOST: (1 << 8),
    ONGROUND: (1 << 9),
    PARTIALGROUND: (1 << 10),
    WATERJUMP: (1 << 11),
    FROZEN: (1 << 12),
    FAKECLIENT: (1 << 13),
    DUCKING: (1 << 14),
    FLOAT: (1 << 15),
    GRAPHED: (1 << 16),
    IMMUNE_WATER: (1 << 17),
    IMMUNE_SLIME: (1 << 18),
    IMMUNE_LAVA: (1 << 19),
    PROXY: (1 << 20),
    ALWAYSTHINK: (1 << 21),
    BASEVELOCITY: (1 << 22),
    MONSTERCLIP: (1 << 23),
    ONTRAIN: (1 << 24),
    WORLDBRUSH: (1 << 25),
    SPECTATOR: (1 << 26),
    CUSTOMENTITY: (1 << 29),
    KILLME: (1 << 30),
    DORMANT: (1 << 31),
});

const buttons = Object.freeze({
    ATTACK: (1 << 0),
    JUMP: (1 << 1),
    DUCK: (1 << 2),
    FORWARD: (1 << 3),
    BACK: (1 << 4),
    USE: (1 << 5),
    CANCEL: (1 << 6),
    LEFT: (1 << 7),
    RIGHT: (1 << 8),
    MOVELEFT: (1 << 9),
    MOVERIGHT: (1 << 10),
    ATTACK2: (1 << 11),
    RUN: (1 << 12),
    RELOAD: (1 << 13),
    ALT1: (1 << 14),
    SCORE: (1 << 15),
});

const movetype = Object.freeze({
    NONE: 0,
    ANGLENOCLIP: 1,
    ANGLECLIP: 2,
    WALK: 3,
    STEP: 4,
    FLY: 5,
    TOSS: 6,
    PUSH: 7,
    NOCLIP: 8,
    FLYMISSILE: 9,
    BOUNCE: 10,
    BOUNCEMISSILE: 11,
    FOLLOW: 12,
    PUSHSTEP: 13,
});

const obs = Object.freeze({
    NONE: 0,
    CHASE_LOCKED: 1,
    CHASE_FREE: 2,
    ROAMING: 3,
    IN_EYE: 4,
    MAP_FREE: 5,
    MAP_CHASE: 6,
});

export {flags, buttons, movetype, obs};

